### ISSUE TITLE
Multiple music tracks could be played in main menu

### ISSUE THREAD

**Issue by alexander4308** [RelativityMC/raise-sound-limit-simplified#10]
**Describe the bug**
After logging out from singleplayer world into a main menu there is a chance of multiple music tracks will be played at the same time.

**To Reproduce**
I don't know any precise steps to reproduce it, however, here the steps i do in order to bug it:
1. Set an audio device to specific one in custom settings. You don't have to set it in every attempt.
2. Login into a new world.
3. Do casual gameplay.
4. Occasionally send `/stopsound @s` command
5. Log out from world.
6. Repeat till it breaks.

**Expected behavior**
Only one or none music track should play in the main menu.

**Runtime info (please complete the following information):**
 - OS: Windows 11
 - Minecraft version: 1.21.1
 - Mod version: 1.1.4

**Crash reports / logs**
https://paste.nolog.cz/?34d9faacd3b39744#FySvNNST8gtoxF1XcgiacM5WcG65SSxCbG24H6DAKxEu

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by Spike-has-no-idea-how-to-code** [comment]
seconded, this has happened to me as well

**Comment by ishland** [comment]
Fixed in 1.1.6.
