### ISSUE TITLE
I don't know why, but this mod does not work on my main PC. Other mods work, and they work on different PCs.

### ISSUE THREAD

**Issue by ioldtype** [RelativityMC/raise-sound-limit-simplified#5]
I don't know why, but this mod does not work on my main PC. Other mods work, and they work on different PCs.

**To Reproduce**
1.Install a mod.
2. Minecraft works fine, but the value of the SOUND limit does not change.

**Screenshots**
![Desktop Screenshot 2023 10 21 - 16 48 11 78](https://github.com/RelativityMC/raise-sound-limit-simplified/assets/148515730/54004a00-6040-47df-9c0b-8884ccdf33af)

**Runtime info (please complete the following information):**
 - OS: Windows11
 - Minecraft version: 1.18.2
 - Mod version: 1.18.2

**Other mods**

**Checklist**

 - [ x] I am using the official version of the mod. 
 - [x ] I tried the latest development version but the issue persists. 
 - [ x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by ioldtype** [comment]
Initializing the PC and changing from windows 11 to windows 10 did not solve this problem.

**Comment by ishland** [comment]
This is likely caused by non-ascii characters on the path to your `%AppData%`. This should already be fixed months ago. Are you sure it does still happen with the latest development build?

**Comment by ioldtype** [comment]
Yes it happens in rsls-1.0.1 too.

**Comment by ioldtype** [comment]
I initialized the PC again and changed the name to alphabetical and was able to do it. Thank you very much.

**Comment by ioldtype** [comment]
Thank you!!!!

![Desktop Screenshot 2023 10 22 - 20 41 36 57](https://github.com/RelativityMC/raise-sound-limit-simplified/assets/148515730/ec906ed3-c32e-4e03-9d61-10e0fa584e03)

**Comment by ioldtype** [comment]
Thank you!!!!
https://youtu.be/apvAPWk1eF8

**Comment by ishland** [comment]
> Yes it happens in rsls-1.0.1 too.

By development build I mean [this currently](https://github.com/RelativityMC/raise-sound-limit-simplified/actions/runs/6602369115). It can be found in the Actions tab.

**Comment by ioldtype** [comment]
Thank you!!
