### ISSUE TITLE
Might need some assistance

### ISSUE THREAD

**Issue by MrBlackmidi** [RelativityMC/raise-sound-limit-simplified#8]
I tried to use this mod (with and without fabric just fyi) and the game crasged with this error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_359 failed

**Comment by MrBlackmidi** [comment]
just to mention, i was using 1.20.4 which may not be supported yet and the non fabric test was on 1.20.2

**Comment by ishland** [comment]
1.20.4 support isn't released yet. And don't delete the entire issue template.
